[keys.normal]
D = ["kill_to_line_end"]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
"$" = "goto_line_end"
"0" = "goto_first_nonwhitespace"
G = "goto_file_end"
esc = ["collapse_selection", "keep_primary_selection"]
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"C-r" = "redo"

[keys.normal.'\']
w = ":write"     
